# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ingredients = [
  { ingredient_name: "Almond Flour", volume: 1, unit: "cup", ounces: 3.375, grams: 96 },
  { ingredient_name: "Almond paste (packed)", volume: 1, unit: "cup", ounces: 9.125, grams: 259 },
  { ingredient_name: "Almonds (sliced)", volume: 1, unit: "cup", ounces: 3, grams: 86 },
  { ingredient_name: "Almonds (slivered)", volume: 1, unit: "cup", ounces: 4, grams: 114 },
  { ingredient_name: "Almonds, whole (unblanched)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Amaranth flour", volume: 1, unit: "cup", ounces: 3.625, grams: 103 },
  { ingredient_name: "Ancient Grains", volume: 1, unit: "cup", ounces: 4.625, grams: 113 },
  { ingredient_name: "Apples (dried, diced)", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Apples (peeled, sliced)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Apricots (dried, diced)", volume: 1, unit: "cup", ounces: 4.5, grams: 128 },
  { ingredient_name: "Baker’s Cinnamon Filling", volume: 1, unit: "cup", ounces: 5.375, grams: 152 },
  { ingredient_name: "Baking powder", volume: 1, unit: "tablespoon", ounces: 0, grams: 12 },
  { ingredient_name: "Baking Sheet brownie mix (dry)", volume: 1, unit: "cup", ounces: 5.75, grams: 163 },
  { ingredient_name: "Baking soda", volume: 1, unit: "tablespoon", ounces: 0, grams: 18 },
  { ingredient_name: "Bananas (mashed)", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Barley (cooked)", volume: 1, unit: "cup", ounces: 7.625, grams: 215 },
  { ingredient_name: "Barley flakes", volume: 1, unit: "cup", ounces: 3.25, grams: 92 },
  { ingredient_name: "Barley flour", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Barley, pearled", volume: 1, unit: "cup", ounces: 7.5, grams: 213 },
  { ingredient_name: "Basil pesto", volume: 1, unit: "tablespoon", ounces: 0.5, grams: 14 },
  { ingredient_name: "Berries (frozen)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Blueberries (dried)", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Blueberries (fresh)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Boiled cider", volume: 1, unit: "cup", ounces: 12, grams: 340 },
  { ingredient_name: "Bran cereal", volume: 1, unit: "cup", ounces: 2.125, grams: 60 },
  { ingredient_name: "Bread crumbs (dried)", volume: 1, unit: "cup", ounces: 4, grams: 112 },
  { ingredient_name: "Bread crumbs (fresh)", volume: 1, unit: "cup", ounces: 1.5, grams: 42 },
  { ingredient_name: "Bread crumbs, Japanese Panko", volume: 1, unit: "cup", ounces: 1.75, grams: 50 },
  { ingredient_name: "Bread Flour", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Buckwheat Flour", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Buckwheat, whole (kasha)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Bulgur", volume: 1, unit: "cup", ounces: 5.375, grams: 152 },
  { ingredient_name: "Butter", volume: 1, unit: "cup", ounces: 8, grams: 226 },
  { ingredient_name: "Buttermilk Powder", volume: 1, unit: "tablespoon", ounces: 0.4375, grams: 12.5 },
  { ingredient_name: "Buttermilk, yogurt, sour cream", volume: 1, unit: "tablespoon", ounces: 0.5, grams: 14 },
  { ingredient_name: "Candied Peel", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Caramel bits (Heath or chopped toffee)", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Caramel, 14-16 individual pieces", volume: 1, unit: "cup", ounces: 10, grams: 284 },
  { ingredient_name: "Caraway seeds", volume: 1, unit: "tablespoon", ounces: 0.3125, grams: 9 },
  { ingredient_name: "Carrots (cooked and puréed)", volume: 1, unit: "cup", ounces: 9, grams: 256 },
  { ingredient_name: "Carrots (diced)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Carrots (grated)", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Cashews (chopped)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Cashews (whole)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Celery (diced)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Cheese powder", volume: 1, unit: "cup", ounces: 4, grams: 114 },
  { ingredient_name: "Cheese, cheddar, jack, mozzarella, Swiss (grated)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Cheese, Feta", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Cheese, Parmesan (grated)", volume: 1, unit: "cup", ounces: 3.5, grams: 100 },
  { ingredient_name: "Cheese, Ricotta", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Cherries (candied)", volume: 1, unit: "cup", ounces: 7, grams: 200 },
  { ingredient_name: "Cherries (dried)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Cherries (frozen)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Chickpea flour", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Chives (fresh)", volume: 1, unit: "cup", ounces: 1.5, grams: 42 },
  { ingredient_name: "Chocolate (chopped)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Chocolate chips", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Cocoa, unsweetened", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Coconut Flour", volume: 1, unit: "cup", ounces: 4.5, grams: 128 },
  { ingredient_name: "Coconut milk powder", volume: 1, unit: "cup", ounces: 4, grams: 114 },
  { ingredient_name: "Coconut, sweetened (shredded)", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Coconut, unsweetened (large flakes)", volume: 1, unit: "cup", ounces: 2.125, grams: 60 },
  { ingredient_name: "Coconut, unsweetened (shredded)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Coffee powder", volume: 1, unit: "tablespoon", ounces: 0.1875, grams: 6 },
  { ingredient_name: "Cookie crumbs", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Corn (popped)", volume: 1, unit: "cup", ounces: 0.1875, grams: 5.25 },
  { ingredient_name: "Corn syrup", volume: 1, unit: "cup", ounces: 11, grams: 312 },
  { ingredient_name: "Cornmeal, whole", volume: 1, unit: "cup", ounces: 4.875, grams: 138 },
  { ingredient_name: "Cornmeal, yellow, Quaker", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Cornstarch", volume: 1, unit: "cup", ounces: 4, grams: 112 },
  { ingredient_name: "Cranberries (dried)", volume: 1, unit: "cup", ounces: 4, grams: 114 },
  { ingredient_name: "Cranberries (fresh or frozen)", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Cream (heavy, light, or half & half)", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Cream cheese", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Currants", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Dates (chopped)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Durum Flour", volume: 1, unit: "cup", ounces: 4.375, grams: 124 },
  { ingredient_name: "Egg white (fresh)", volume: 1, unit: "large", ounces: 1.25, grams: 35 },
  { ingredient_name: "Egg yolk (fresh)", volume: 1, unit: "large", ounces: 0.5, grams: 14 },
  { ingredient_name: "Espresso powder", volume: 1, unit: "tablespoon", ounces: 0.25, grams: 7 },
  { ingredient_name: "Figs (dried, chopped)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Flax meal", volume: 1, unit: "cup", ounces: 3.5, grams: 100 },
  { ingredient_name: "Flaxseed", volume: 1, unit: "cup", ounces: 5, grams: 140 },
  { ingredient_name: "Garlic (cloves, in skin for roasting)", volume: 1, unit: "head", ounces: 4, grams: 113 },
  { ingredient_name: "Garlic (minced)", volume: 1, unit: "tablespoon", ounces: 0.5, grams: 14 },
  { ingredient_name: "Garlic (peeled and sliced)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Ginger (crystallized)", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Ginger (fresh, sliced)", volume: 1, unit: "cup", ounces: 8, grams: 228 },
  { ingredient_name: "Graham cracker crumbs (boxed)", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Graham crackers (crushed)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Granola", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Grape Nuts", volume: 1, unit: "cup", ounces: 4, grams: 114 },
  { ingredient_name: "Hazelnut Flour", volume: 1, unit: "cup", ounces: 3.125, grams: 89 },
  { ingredient_name: "Hazelnuts (whole)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "High-Gluten Flour", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Honey", volume: 1, unit: "cup", ounces: 12, grams: 340 },
  { ingredient_name: "Italian-Style 00", volume: 1, unit: "cup", ounces: 3.75, grams: 106 },
  { ingredient_name: "Jam or preserves", volume: 1, unit: "cup", ounces: 12, grams: 340 },
  { ingredient_name: "Lard", volume: 1, unit: "cup", ounces: 8, grams: 226 },
  { ingredient_name: "Leeks (diced)", volume: 1, unit: "cup", ounces: 3.25, grams: 92 },
  { ingredient_name: "Macadamia nuts (whole)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Malt syrup", volume: 1, unit: "tablespoon", ounces: 0.75, grams: 21.5 },
  { ingredient_name: "Malted milk powder", volume: 1, unit: "cup", ounces: 5, grams: 140 },
  { ingredient_name: "Malted Wheat Flakes", volume: 1, unit: "cup", ounces: 4.5, grams: 128 },
  { ingredient_name: "Maple Flav-R-Bites", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Maple sugar", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Maple syrup", volume: 1, unit: "cup", ounces: 11, grams: 312 },
  { ingredient_name: "Marshmallow crème", volume: 1, unit: "cup", ounces: 3, grams: 85 },
  { ingredient_name: "Marshmallow Fluff®", volume: 1, unit: "cup", ounces: 4.5, grams: 128 },
  { ingredient_name: "Marshmallows (mini)", volume: 1, unit: "cup", ounces: 1.5, grams: 43 },
  { ingredient_name: "Mayonnaise", volume: 1, unit: "cup", ounces: 8, grams: 226 },
  { ingredient_name: "Meringue powder", volume: 1, unit: "cup", ounces: 6, grams: 172 },
  { ingredient_name: "Milk, 1%", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Milk, baker’s special dry", volume: 1, unit: "cup", ounces: 5, grams: 140 },
  { ingredient_name: "Milk, evaporated", volume: 1, unit: "cup", ounces: 9, grams: 256 },
  { ingredient_name: "Milk, store bought nonfat dry", volume: 1, unit: "cup", ounces: 3, grams: 84 },
  { ingredient_name: "Milk, sweetened condensed", volume: 1, unit: "cup", ounces: 11, grams: 312 },
  { ingredient_name: "Millet (whole)", volume: 1, unit: "cup", ounces: 7.25, grams: 206 },
  { ingredient_name: "Molasses", volume: 1, unit: "cup", ounces: 12, grams: 340 },
  { ingredient_name: "Mushrooms (sliced)", volume: 1, unit: "cup", ounces: 2.75, grams: 78 },
  { ingredient_name: "Oat bran", volume: 1, unit: "cup", ounces: 3.75, grams: 106 },
  { ingredient_name: "Oat Flour", volume: 1, unit: "cup", ounces: 3.25, grams: 92 },
  { ingredient_name: "Oats, quick cooking", volume: 1, unit: "cup", ounces: 3.125, grams: 89 },
  { ingredient_name: "Oats, steel cut (cooked)", volume: 1, unit: "cup", ounces: 9, grams: 255 },
  { ingredient_name: "Oats, steel cut (raw)", volume: 1, unit: "cup", ounces: 5.75, grams: 198 },
  { ingredient_name: "Oats, traditional rolled or thick flakes", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Oil, vegetable", volume: 1, unit: "cup", ounces: 7, grams: 198 },
  { ingredient_name: "Olives (sliced)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Onions, baking", volume: 1, unit: "cup", ounces: 2.75, grams: 0 },
  { ingredient_name: "Onions, fresh (diced)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Organic 6-Grain Flakes", volume: 1, unit: "cup", ounces: 7.25, grams: 206 },
  { ingredient_name: "Pastry Flour Blend", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Peaches (peeled and diced)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Peanut butter", volume: 1, unit: "cup", ounces: 9.5, grams: 270 },
  { ingredient_name: "Peanuts (whole, shelled)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Pears (peeled and diced)", volume: 1, unit: "cup", ounces: 5.75, grams: 163 },
  { ingredient_name: "Pecans (diced)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Peppers, red or green (fresh)", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Perfect Pasta Blend", volume: 1, unit: "cup", ounces: 5.125, grams: 145 },
  { ingredient_name: "Perfect Pizza Blend", volume: 1, unit: "cup", ounces: 4.375, grams: 124 },
  { ingredient_name: "Persimmon pulp", volume: 1, unit: "cup", ounces: 8.5, grams: 241 },
  { ingredient_name: "Pie Filling Enhancer", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Pine nuts", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Pineapple (fresh or canned, diced)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Pineapple, dried", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Pistachio nut paste", volume: 1, unit: "cup", ounces: 11, grams: 312 },
  { ingredient_name: "Pistachio nuts", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Polenta (coarse ground cornmeal)", volume: 1, unit: "cup", ounces: 5.75, grams: 163 },
  { ingredient_name: "Poppy seeds", volume: 1, unit: "cup", ounces: 5.5, grams: 0 },
  { ingredient_name: "Potato Flour", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Potato Starch", volume: 1, unit: "cup", ounces: 5.375, grams: 152 },
  { ingredient_name: "Potatoes (mashed)", volume: 1, unit: "cup", ounces: 7.5, grams: 213 },
  { ingredient_name: "Praline paste", volume: 1, unit: "cup", ounces: 11, grams: 312 },
  { ingredient_name: "Pumpkin (canned)", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Quinoa (cooked)", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Quinoa (whole)", volume: 1, unit: "cup", ounces: 6.25, grams: 177 },
  { ingredient_name: "Quinoa flour", volume: 1, unit: "cup", ounces: 3.875, grams: 110 },
  { ingredient_name: "Raisins (loose)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Raisins (packed)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Raspberries (fresh)", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Rhubarb (fresh, medium dice)", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Rice flour", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Rice Krispies", volume: 1, unit: "cup", ounces: 1, grams: 28 },
  { ingredient_name: "Rice, brown (cooked)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Rice, long grain (dry)", volume: 1, unit: "cup", ounces: 7, grams: 198 },
  { ingredient_name: "Rye flakes", volume: 1, unit: "cup", ounces: 4.375, grams: 124 },
  { ingredient_name: "Rye Flour", volume: 1, unit: "cup", ounces: 3.75, grams: 106 },
  { ingredient_name: "Scallions (sliced)", volume: 1, unit: "cup", ounces: 2.25, grams: 64 },
  { ingredient_name: "Self-Rising Flour", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Semolina Flour", volume: 1, unit: "cup", ounces: 5.75, grams: 163 },
  { ingredient_name: "Sesame seeds", volume: 1, unit: "cup", ounces: 5, grams: 142 },
  { ingredient_name: "Shallots (peeled and sliced)", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Sorghum flour", volume: 1, unit: "cup", ounces: 4.875, grams: 138 },
  { ingredient_name: "Sour cream", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Sourdough starter", volume: 1, unit: "cup", ounces: 8.5, grams: 241 },
  { ingredient_name: "Soy flour", volume: 1, unit: "cup", ounces: 5, grams: 140 },
  { ingredient_name: "Spelt Flour", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Sprouted Wheat Flour", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Strawberries (fresh sliced)", volume: 1, unit: "cup", ounces: 5.875, grams: 167 },
  { ingredient_name: "Sugar (granulated white)", volume: 1, unit: "cup", ounces: 7, grams: 198 },
  { ingredient_name: "Sugar, confectioners' (unsifted)", volume: 1, unit: "cup", ounces: 4, grams: 113.5 },
  { ingredient_name: "Sugar, dark or light brown (packed)", volume: 1, unit: "cup", ounces: 7.5, grams: 213 },
  { ingredient_name: "Sugar, demerara", volume: 1, unit: "cup", ounces: 7.75, grams: 220 },
  { ingredient_name: "Sugar, sticky bun", volume: 1, unit: "cup", ounces: 3.5, grams: 99 },
  { ingredient_name: "Sundried tomatoes (dry pack)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
  { ingredient_name: "Sunflower seeds", volume: 1, unit: "cup", ounces: 5, grams: 140 },
  { ingredient_name: "Tahini paste", volume: 1, unit: "cup", ounces: 9, grams: 256 },
  { ingredient_name: "Tapioca (quick-cooking)", volume: 1, unit: "tablespoon", ounces: 0.375, grams: 10.5 },
  { ingredient_name: "Tapioca Starch or flour", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Teff flour", volume: 1, unit: "cup", ounces: 4.75, grams: 135 },
  { ingredient_name: "Toffee chunks", volume: 1, unit: "cup", ounces: 5.5, grams: 156 },
  { ingredient_name: "Unbleached All-Purpose Flour", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Unbleached Cake Flour", volume: 1, unit: "cup", ounces: 4.25, grams: 120 },
  { ingredient_name: "Unbleached Pastry Flour", volume: 1, unit: "cup", ounces: 3.75, grams: 106 },
  { ingredient_name: "Vegetable shortening", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Walnuts (chopped)", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Walnuts (whole)", volume: 1, unit: "cup", ounces: 4.5, grams: 128 },
  { ingredient_name: "Water", volume: 1, unit: "cup", ounces: 7.875, grams: 222 },
  { ingredient_name: "Wheat (cracked)", volume: 1, unit: "cup", ounces: 5.25, grams: 149 },
  { ingredient_name: "Wheat berries (red)", volume: 1, unit: "cup", ounces: 6.5, grams: 184 },
  { ingredient_name: "Wheat bran", volume: 1, unit: "cup", ounces: 2.25, grams: 64 },
  { ingredient_name: "Wheat flakes (malted)", volume: 1, unit: "cup", ounces: 4, grams: 112 },
  { ingredient_name: "Wheat germ", volume: 1, unit: "cup", ounces: 4, grams: 112 },
  { ingredient_name: "Whole Wheat Flour", volume: 1, unit: "cup", ounces: 4, grams: 113 },
  { ingredient_name: "Whole Wheat Pastry Flour", volume: 1, unit: "cup", ounces: 3.375, grams: 96 },
  { ingredient_name: "Yeast (instant)", volume: 1, unit: "tablespoon", ounces: 0.333333333333333, grams: 9.33333333333333 },
  { ingredient_name: "Yogurt", volume: 1, unit: "cup", ounces: 8, grams: 227 },
  { ingredient_name: "Zucchini (shredded)", volume: 1, unit: "cup", ounces: 6, grams: 170 },
]
