ingredients = [
  { ingredient_name: "Almond Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.375, ingredient_grams: 96 },
  { ingredient_name: "Almond paste (packed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9.125, ingredient_grams: 259 },
  { ingredient_name: "Almonds (sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 86 },
  { ingredient_name: "Almonds (slivered)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 114 },
  { ingredient_name: "Almonds, whole (unblanched)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Amaranth flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.625, ingredient_grams: 103 },
  { ingredient_name: "Ancient Grains", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.625, ingredient_grams: 113 },
  { ingredient_name: "Apples (dried, diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Apples (peeled, sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Apricots (dried, diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.5, ingredient_grams: 128 },
  { ingredient_name: "Baker’s Cinnamon Filling", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.375, ingredient_grams: 152 },
  { ingredient_name: "Baking powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_grams: 192 },
  { ingredient_name: "Baking Sheet brownie mix (dry)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.75, ingredient_grams: 163 },
  { ingredient_name: "Baking soda", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_grams: 288 },
  { ingredient_name: "Bananas (mashed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Barley (cooked)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.625, ingredient_grams: 215 },
  { ingredient_name: "Barley flakes", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.25, ingredient_grams: 92 },
  { ingredient_name: "Barley flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Barley, pearled", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.5, ingredient_grams: 213 },
  { ingredient_name: "Basil pesto", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 224 },
  { ingredient_name: "Berries (frozen)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Blueberries (dried)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Blueberries (fresh)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Boiled cider", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 12, ingredient_grams: 340 },
  { ingredient_name: "Bran cereal", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 2.125, ingredient_grams: 60 },
  { ingredient_name: "Bread crumbs (dried)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 112 },
  { ingredient_name: "Bread crumbs (fresh)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 1.5, ingredient_grams: 42 },
  { ingredient_name: "Bread crumbs, Japanese Panko", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 1.75, ingredient_grams: 50 },
  { ingredient_name: "Bread Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Buckwheat Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Buckwheat, whole (kasha)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Bulgur", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.375, ingredient_grams: 152 },
  { ingredient_name: "Butter", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 226 },
  { ingredient_name: "Buttermilk Powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7, ingredient_grams: 200 },
  { ingredient_name: "Buttermilk, yogurt, sour cream", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 224 },
  { ingredient_name: "Candied Peel", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Caramel bits (Heath or chopped toffee)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Caramel, 14-16 individual pieces", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 10, ingredient_grams: 284 },
  { ingredient_name: "Caraway seeds", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 144 },
  { ingredient_name: "Carrots (cooked and puréed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9, ingredient_grams: 256 },
  { ingredient_name: "Carrots (diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Carrots (grated)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 99 },
  { ingredient_name: "Cashews (chopped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Cashews (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Celery (diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Cheese powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 114 },
  { ingredient_name: "Cheese, cheddar, jack, mozzarella, Swiss (grated)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Cheese, Feta", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Cheese, Parmesan (grated)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 100 },
  { ingredient_name: "Cheese, Ricotta", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Cherries (candied)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7, ingredient_grams: 200 },
  { ingredient_name: "Cherries (dried)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Cherries (frozen)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Chickpea flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Chives (fresh)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 1.5, ingredient_grams: 42 },
  { ingredient_name: "Chocolate (chopped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Chocolate chips", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Cocoa, unsweetened", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Coconut Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.5, ingredient_grams: 128 },
  { ingredient_name: "Coconut milk powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 114 },
  { ingredient_name: "Coconut, sweetened (shredded)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Coconut, unsweetened (large flakes)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 2.125, ingredient_grams: 60 },
  { ingredient_name: "Coconut, unsweetened (shredded)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Coffee powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 96 },
  { ingredient_name: "Cookie crumbs", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Corn (popped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 0.1875, ingredient_grams: 5.25 },
  { ingredient_name: "Corn syrup", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 11, ingredient_grams: 312 },
  { ingredient_name: "Cornmeal, whole", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.875, ingredient_grams: 138 },
  { ingredient_name: "Cornmeal, yellow, Quaker", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Cornstarch", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 112 },
  { ingredient_name: "Cranberries (dried)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 114 },
  { ingredient_name: "Cranberries (fresh or frozen)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 99 },
  { ingredient_name: "Cream (heavy, light, or half & half)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Cream cheese", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Currants", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Dates (chopped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Durum Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.375, ingredient_grams: 124 },
  { ingredient_name: "Egg white (fresh, large)", ingredient_volume: 1, ingredient_unit: "Egg", ingredient_ounces: 1.25, ingredient_grams: 35 },
  { ingredient_name: "Egg yolk (fresh, large)", ingredient_volume: 1, ingredient_unit: "Egg", ingredient_ounces: 0.5, ingredient_grams: 14 },
  { ingredient_name: "Espresso powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 112 },
  { ingredient_name: "Figs (dried, chopped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Flax meal", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 100 },
  { ingredient_name: "Flaxseed", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 140 },
  { ingredient_name: "Garlic (minced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 224 },
  { ingredient_name: "Garlic (peeled and sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Ginger (crystallized)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Ginger (fresh, sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 228 },
  { ingredient_name: "Graham cracker crumbs (boxed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 99 },
  { ingredient_name: "Graham crackers (crushed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Granola", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Grape Nuts", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 114 },
  { ingredient_name: "Hazelnut Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.125, ingredient_grams: 89 },
  { ingredient_name: "Hazelnuts (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "High-Gluten Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Honey", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 12, ingredient_grams: 340 },
  { ingredient_name: "Italian-Style 00", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.75, ingredient_grams: 106 },
  { ingredient_name: "Jam or preserves", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 12, ingredient_grams: 340 },
  { ingredient_name: "Lard", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 226 },
  { ingredient_name: "Leeks (diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.25, ingredient_grams: 92 },
  { ingredient_name: "Macadamia nuts (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Malt syrup", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 12, ingredient_grams: 344 },
  { ingredient_name: "Malted milk powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 140 },
  { ingredient_name: "Malted Wheat Flakes", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.5, ingredient_grams: 128 },
  { ingredient_name: "Maple Flav-R-Bites", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Maple sugar", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Maple syrup", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 11, ingredient_grams: 312 },
  { ingredient_name: "Marshmallow crème", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 85 },
  { ingredient_name: "Marshmallow Fluff®", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.5, ingredient_grams: 128 },
  { ingredient_name: "Marshmallows (mini)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 1.5, ingredient_grams: 43 },
  { ingredient_name: "Mayonnaise", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 226 },
  { ingredient_name: "Meringue powder", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 172 },
  { ingredient_name: "Milk, 1%", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Milk, baker’s special dry", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 140 },
  { ingredient_name: "Milk, evaporated", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9, ingredient_grams: 256 },
  { ingredient_name: "Milk, store bought nonfat dry", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3, ingredient_grams: 84 },
  { ingredient_name: "Milk, sweetened condensed", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 11, ingredient_grams: 312 },
  { ingredient_name: "Millet (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.25, ingredient_grams: 206 },
  { ingredient_name: "Molasses", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 12, ingredient_grams: 340 },
  { ingredient_name: "Mushrooms (sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 2.75, ingredient_grams: 78 },
  { ingredient_name: "Oat bran", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.75, ingredient_grams: 106 },
  { ingredient_name: "Oat Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.25, ingredient_grams: 92 },
  { ingredient_name: "Oats, quick cooking", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.125, ingredient_grams: 89 },
  { ingredient_name: "Oats, steel cut (cooked)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9, ingredient_grams: 255 },
  { ingredient_name: "Oats, steel cut (raw)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.75, ingredient_grams: 198 },
  { ingredient_name: "Oats, traditional rolled or thick flakes", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 99 },
  { ingredient_name: "Oil, vegetable", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7, ingredient_grams: 198 },
  { ingredient_name: "Olives (sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Onions, fresh (diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Organic 6-Grain Flakes", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.25, ingredient_grams: 206 },
  { ingredient_name: "Pastry Flour Blend", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Peaches (peeled and diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Peanut butter", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9.5, ingredient_grams: 270 },
  { ingredient_name: "Peanuts (whole, shelled)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Pears (peeled and diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.75, ingredient_grams: 163 },
  { ingredient_name: "Pecans (diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Peppers, red or green (fresh)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Perfect Pasta Blend", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.125, ingredient_grams: 145 },
  { ingredient_name: "Perfect Pizza Blend", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.375, ingredient_grams: 124 },
  { ingredient_name: "Persimmon pulp", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8.5, ingredient_grams: 241 },
  { ingredient_name: "Pie Filling Enhancer", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Pine nuts", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Pineapple (fresh or canned, diced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Pineapple, dried", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Pistachio nut paste", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 11, ingredient_grams: 312 },
  { ingredient_name: "Pistachio nuts", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Polenta (coarse ground cornmeal)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.75, ingredient_grams: 163 },
  { ingredient_name: "Poppy seeds", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 36 },
  { ingredient_name: "Potato Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Potato Starch", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.375, ingredient_grams: 152 },
  { ingredient_name: "Potatoes (mashed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.5, ingredient_grams: 213 },
  { ingredient_name: "Praline paste", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 11, ingredient_grams: 312 },
  { ingredient_name: "Pumpkin (canned)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Quinoa (cooked)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Quinoa (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.25, ingredient_grams: 177 },
  { ingredient_name: "Quinoa flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.875, ingredient_grams: 110 },
  { ingredient_name: "Raisins (loose)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Raisins (packed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Raspberries (fresh)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Rhubarb (fresh, medium dice)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Rice flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Rice Krispies", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 1, ingredient_grams: 28 },
  { ingredient_name: "Rice, brown (cooked)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Rice, long grain (dry)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7, ingredient_grams: 198 },
  { ingredient_name: "Rye flakes", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.375, ingredient_grams: 124 },
  { ingredient_name: "Rye Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.75, ingredient_grams: 106 },
  { ingredient_name: "Scallions (sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 2.25, ingredient_grams: 64 },
  { ingredient_name: "Self-Rising Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Semolina Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.75, ingredient_grams: 163 },
  { ingredient_name: "Sesame seeds", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 142 },
  { ingredient_name: "Shallots (peeled and sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Sorghum flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.875, ingredient_grams: 138 },
  { ingredient_name: "Sour cream", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Sourdough starter", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8.5, ingredient_grams: 241 },
  { ingredient_name: "Soy flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 140 },
  { ingredient_name: "Spelt Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.5, ingredient_grams: 99 },
  { ingredient_name: "Sprouted Wheat Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Strawberries (fresh sliced)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.875, ingredient_grams: 167 },
  { ingredient_name: "Sugar (granulated white)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7, ingredient_grams: 198 },
  { ingredient_name: "Sugar, confectioners' (unsifted)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113.5 },
  { ingredient_name: "Sugar, dark or light brown (packed)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.5, ingredient_grams: 213 },
  { ingredient_name: "Sugar, demerara", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.75, ingredient_grams: 220 },
  { ingredient_name: "Sundried tomatoes (dry pack)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 },
  { ingredient_name: "Sunflower seeds", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5, ingredient_grams: 140 },
  { ingredient_name: "Tahini paste", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 9, ingredient_grams: 256 },
  { ingredient_name: "Tapioca (quick-cooking)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 168 },
  { ingredient_name: "Tapioca Starch or flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Teff flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.75, ingredient_grams: 135 },
  { ingredient_name: "Toffee chunks", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.5, ingredient_grams: 156 },
  { ingredient_name: "Unbleached All-Purpose Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Unbleached Cake Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.25, ingredient_grams: 120 },
  { ingredient_name: "Unbleached Pastry Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.75, ingredient_grams: 106 },
  { ingredient_name: "Vegetable shortening", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Walnuts (chopped)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Walnuts (whole)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4.5, ingredient_grams: 128 },
  { ingredient_name: "Water", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 7.875, ingredient_grams: 222 },
  { ingredient_name: "Wheat (cracked)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.25, ingredient_grams: 149 },
  { ingredient_name: "Wheat berries (red)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6.5, ingredient_grams: 184 },
  { ingredient_name: "Wheat bran", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 2.25, ingredient_grams: 64 },
  { ingredient_name: "Wheat flakes (malted)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 112 },
  { ingredient_name: "Wheat germ", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 112 },
  { ingredient_name: "Whole Wheat Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 4, ingredient_grams: 113 },
  { ingredient_name: "Whole Wheat Pastry Flour", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 3.375, ingredient_grams: 96 },
  { ingredient_name: "Yeast (instant)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 5.33333333333333, ingredient_grams: 149.333333333333 },
  { ingredient_name: "Yogurt", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 8, ingredient_grams: 227 },
  { ingredient_name: "Zucchini (shredded)", ingredient_volume: 1, ingredient_unit: "Cups", ingredient_ounces: 6, ingredient_grams: 170 }
]

ingredients.each {|ingredient| Ingredient.create(ingredient)}
